from trt.config.stage_config import (
    PipelineConfig,
    PipelineHooks,
    StageConfig,
    StageHooks,
    StageKind,
)
from trt.io_spec import GROOT_EDGE_IO

_E = "trt.executor.models.groot.export"

GROOT_PIPELINE = PipelineConfig(
    model_type="Gr00tN1d7",
    hooks=PipelineHooks(
        preprocess=f"{_E}.preprocess:preprocess",
        postprocess=f"{_E}.postprocess:postprocess",
    ),
    stages=(
        StageConfig(
            stage_id=0,
            kind=StageKind.VISION_ENCODE,
            input_sources=(),
            runner="trt.runner.export:ExportRunner",
            io=GROOT_EDGE_IO.vision,
            engine_subdir="visual",
            hooks=StageHooks(
                plan_export=f"{_E}.vision:plan_export",
                compile=f"{_E}.vision:compile",
                metadata=f"{_E}.vision:metadata",
            ),
        ),
        StageConfig(
            stage_id=1,
            kind=StageKind.LANGUAGE_PREFILL,
            input_sources=(0,),
            runner="trt.runner.export:ExportRunner",
            io=GROOT_EDGE_IO.language,
            engine_subdir="language",
            hooks=StageHooks(
                process_inputs=f"{_E}.glue:vision_to_language",
                plan_export=f"{_E}.language:plan_export",
                compile=f"{_E}.language:compile",
                save_artifacts=f"{_E}.language:save_artifacts",
                metadata=f"{_E}.language:metadata",
            ),
        ),
        StageConfig(
            stage_id=2,
            kind=StageKind.ACTION_CONTEXT,
            input_sources=(1,),
            runner="trt.runner.export:ExportRunner",
            io=GROOT_EDGE_IO.action_context,
            engine_subdir="action_context",
            hooks=StageHooks(
                process_inputs=f"{_E}.glue:language_to_action_context",
                plan_export=f"{_E}.action_context:plan_export",
                compile=f"{_E}.action_context:compile",
                metadata=f"{_E}.action_context:metadata",
            ),
        ),
        StageConfig(
            stage_id=3,
            kind=StageKind.ACTION_ROLLOUT,
            input_sources=(2,),
            runner="trt.runner.export:ExportRunner",
            io=GROOT_EDGE_IO.action,
            engine_subdir="action",
            final_output=True,
            hooks=StageHooks(
                process_inputs=f"{_E}.glue:action_context_to_action",
                plan_export=f"{_E}.action:plan_export",
                compile=f"{_E}.action:compile",
                metadata=f"{_E}.action:metadata",
            ),
        ),
    ),
)
